debug: false
management.endpoints.web.exposure.include: "*" # ?????? ?????? ??? ?? ???? ?? ???

logging:
  level:
    com.fastcampus.projectboard: debug # ??? ???? ?? ???? ??? ??? ???.
    org.springframework.web.servlet: debug # ??? ???? ?? ???? ??? ??? ???. (debug:false ? ????.)
    org.hibernate.type.descriptor.sql.BasicBinder: trace # ??? ???? ?? ???? TRACE ??? ???. (?? ?? ? ? ? ? ?? ???? ??.)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: revi1337
    password: 1337
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # ????? 2.5.0 ??? ???. (???? ??? ???? ???? ?? ?? ??. ???? ? ???? ????? ?? ??? ??)
    hibernate.ddl-auto: create # ??? ?? entity ? ?? jpa ?? ???? ???? ddl ?? ??? ? ??.
#    open-in-view: false
    show-sql: true # sql ??? ????? ?? (debug ? ?????? ??? true)
    properties: # ???? ????? ???? jpa ?? ??? ???? ??? ???? ??
      hibernate.format_sql: true # ?? ??? ????? ???? ??? ????? ?? ??? ? ??? ????? ???. (??) (??? ??? ???? ??? ???? ?? )
      hibernate.default_batch_fetch_size: 100 # ?? jpa ?? ?? ??? ??? ???? ? ?, ??? select ? ? ? ?? ????. (?? ?? ??????? ??????? row ?? 10? ?? ??? ??? 100?? ??)
  h2.console.enabled: true # ???? db h2 ? ??? ?????.
  sql.init.mode: always # data.sql ? ?? ???? ???? ?? ??.
#  thymeleaf.cache: false
#  data.rest:
#    base-path: /api
#    detection-strategy: annotated
server:
  port: 9005
---
# Test DB ? ??
#spring:
#  config.activate.on-profile: testdb # testdb ????? activate ???? ? ? ??? ??? ?? ?.
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none

